[package]
name = "erebus-core"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
authors = ["Abdallah Dar <dar.abdallah.a@gmail.com>"]

[dependencies]
bitvec = "1.0"
once_cell = "1.19"
num_cpus  = "1.16"

[features]
internal = []