[package]
name = "erebus-table"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
authors = ["Abdallah Dar <dar.abdallah.a@gmail.com>"]

#[dependencies]
#erebus-vector = { path = "../erebus-vector", features = ["internal"] }